#!/usr/bin/env python2.4

import sys
import Noodle
import Noodle.NoodleMain

def title():
    sys.stderr.write("Noodle %s [on Python %s]\n" %
                     (Noodle.version, sys.version.splitlines()[0].strip()))

def usage():
    sys.stderr.write("\nUsage: %s [<noodle-program>]\n" % sys.argv[0])

def main():
    if len(sys.argv) == 1:
        title()
        from Noodle import importing
        from Noodle import interactive
        interactive.main()
        sys.exit(0)
    else:
        del sys.argv[0]
        Noodle.NoodleMain.execfile(sys.argv[0])

if __name__ == "__main__":
    main()
